#!/usr/bin/env python

import subprocess

def get_default():
    list_sinks = []
    stdout, stderr = subprocess.Popen([ 'pacmd', 'list-sinks'], stdout=subprocess.PIPE, stderr=subprocess.STDOUT).communicate()
    stdout = stdout.decode("utf-8").splitlines()
    for line in stdout:
        if '*' in line:
            default_sink_index = len(list_sinks)
        if "index: " in line:
            list_sinks.append(int(line.split()[-1]))

    return default_sink_index, list_sinks


def set_default(d):
    stdout, stderr = subprocess.Popen(['pacmd', 'set-default-sink', str(d)], stdout=subprocess.PIPE, stderr=subprocess.STDOUT).communicate()

def get_sink_inputs():
    sink_list = []
    stdout, stderr = subprocess.Popen(['pacmd', 'list-sink-inputs'], stdout=subprocess.PIPE, stderr=subprocess.STDOUT).communicate()
    stdout = stdout.decode("utf-8").splitlines()
    for line in stdout:
        if 'index: ' in line:
            sink_list.append(int(line.split()[-1]))
    return sink_list

def set_sink_inputs(sink_input_list, d):
    # pactl move-sink-input 87 0
    for s in sink_input_list:
        stdout, stderr = subprocess.Popen(['pacmd', 'move-sink-input', str(s), str(d)], stdout=subprocess.PIPE, stderr=subprocess.STDOUT).communicate()

default_index, list_sinks  = get_default()


default_new = list_sinks[(default_index + 1) % len(list_sinks) ]

set_default(default_new)

set_sink_inputs(get_sink_inputs(), default_new)
