#! /bin/sh


[[ ! $(pidof -x sxhkd) ]] && sxhkd &
relaunch-polybar &

bspc monitor eDP1 -d I II III IV
bspc monitor DP2 -d VIII IX X

bspc config border_width         2
bspc config window_gap          0
# bspc config top_padding 0 # no padding for polybar

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
