#!/bin/sh

case $BLOCK_BUTTON in
	1) notify-send "<b>🖥 CPU hogs</b>:
$(ps axch -o cmd:15,%cpu --sort=-%cpu | head)" ;;
	3) notify-send "<b>🖥 CPU module:</b>
- Shows CPU temperature.
- Click to show intensive processes.
- % is of single core." ;;
esac

cpu_work=$(expr 100 - $(mpstat | tail -c 6 | head -c 2))
cpu_temp=$( sensors | awk '/TC0P/ {print $2 $3}' )

printf "${cpu_work}%% ${cpu_temp}"

